# Generated by Django 2.0 on 2017-12-18 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('cID', models.AutoField(primary_key=True, serialize=False)),
                ('cName', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('oppo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('pID', models.AutoField(primary_key=True, serialize=False)),
                ('pNum', models.IntegerField(unique=True)),
                ('pName', models.CharField(max_length=50)),
                ('stuID', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('tID', models.AutoField(primary_key=True, serialize=False)),
                ('tName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basketR.Team'),
        ),
        migrations.AddField(
            model_name='contest',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basketR.Team'),
        ),
    ]
