# Generated by Django 2.0 on 2017-12-18 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QRecord',
            fields=[
                ('qID', models.AutoField(primary_key=True, serialize=False)),
                ('p2M', models.IntegerField(default=0)),
                ('p2A', models.IntegerField(default=0)),
                ('p3M', models.IntegerField(default=0)),
                ('p3A', models.IntegerField(default=0)),
                ('ftM', models.IntegerField(default=0)),
                ('ftA', models.IntegerField(default=0)),
                ('dR', models.IntegerField(default=0)),
                ('oR', models.IntegerField(default=0)),
                ('ass', models.IntegerField(default=0)),
                ('blk', models.IntegerField(default=0)),
                ('steal', models.IntegerField(default=0)),
                ('turno', models.IntegerField(default=0)),
                ('foul', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='contest',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basketR.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basketR.Team'),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basketR.Contest'),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basketR.Player'),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='q1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basketR.QRecord'),
        ),
    ]
