# Generated by Django 2.0 on 2017-12-18 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketR', '0002_auto_20171218_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='q2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q2', to='basketR.QRecord'),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='q3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q3', to='basketR.QRecord'),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='q4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q4', to='basketR.QRecord'),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='q1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q1', to='basketR.QRecord'),
        ),
    ]
