# Generated by Django 2.0 on 2018-01-12 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketR', '0004_auto_20180112_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerecord',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basketR.Player'),
        ),
    ]
